// Mock users for the application
export const mockUsers = [
  {
    id: 1,
    name: 'Admin User',
    email: 'admin@hotel.com',
    role: 'admin',
    avatar: null,
  },
  {
    id: 2,
    name: 'Staff Member',
    email: 'staff@hotel.com',
    role: 'staff',
    avatar: null,
  },
];

// Mock notifications
export const mockNotifications = [
  {
    id: 1,
    title: 'New Booking',
    description: 'John Doe has booked Room 101 for 3 nights',
    time: '5 mins ago',
    read: false,
  },
  {
    id: 2,
    title: 'Checkout Reminder',
    description: 'Room 205 checkout is due today',
    time: '1 hour ago',
    read: false,
  },
  {
    id: 3,
    title: 'Payment Received',
    description: 'Payment for Invoice #1234 has been received',
    time: '3 hours ago',
    read: true,
  },
  {
    id: 4,
    title: 'Maintenance Request',
    description: 'Maintenance requested for Room 304',
    time: 'Yesterday',
    read: true,
  },
];

// Mock recent activities for the dashboard
export const mockRecentActivities = [
  {
    id: 1,
    type: 'booking',
    description: 'New booking created for Room 101',
    timestamp: '2023-04-25T14:30:00Z',
    user: 'Admin User',
  },
  {
    id: 2,
    type: 'checkout',
    description: 'Guest checked out from Room 205',
    timestamp: '2023-04-25T11:15:00Z',
    user: 'Staff Member',
  },
  {
    id: 3,
    type: 'payment',
    description: 'Payment received for Invoice #1234',
    timestamp: '2023-04-25T09:45:00Z',
    user: 'Admin User',
  },
  {
    id: 4,
    type: 'maintenance',
    description: 'Maintenance completed for Room 304',
    timestamp: '2023-04-24T16:20:00Z',
    user: 'Staff Member',
  },
  {
    id: 5,
    type: 'booking',
    description: 'Booking modified for Room 202',
    timestamp: '2023-04-24T10:30:00Z',
    user: 'Admin User',
  },
];

// Mock rooms data
export const mockRooms = [
  {
    id: 1,
    number: '101',
    type: 'single',
    price: 99,
    capacity: 1,
    amenities: 'Wi-Fi, TV, AC',
    status: 'available',
    description: 'Standard Single',
    floor: 1,
  },
  {
    id: 2,
    number: '102',
    type: 'double',
    price: 149,
    capacity: 2,
    amenities: 'Wi-Fi, TV, AC',
    status: 'occupied',
    description: 'Standard Double',
    floor: 1,
  },
  {
    id: 3,
    number: '201',
    type: 'double',
    price: 199,
    capacity: 2,
    amenities: 'Wi-Fi, TV, AC, Mini Bar',
    status: 'reserved',
    description: 'Deluxe Double',
    floor: 2,
  },
  {
    id: 4,
    number: '202',
    type: 'suite',
    price: 299,
    capacity: 3,
    amenities: 'Wi-Fi, TV, AC, Mini Bar, Jacuzzi',
    status: 'available',
    description: 'Junior Suite',
    floor: 2,
  },
  {
    id: 5,
    number: '301',
    type: 'suite',
    price: 399,
    capacity: 4,
    amenities: 'Wi-Fi, TV, AC, Kitchen, Living Room',
    status: 'available',
    description: 'Executive Suite',
    floor: 3,
  },
  {
    id: 6,
    number: '302',
    type: 'suite',
    price: 499,
    capacity: 4,
    amenities: 'Wi-Fi, TV, AC, Kitchen, Living Room, Jacuzzi',
    status: 'maintenance',
    description: 'Presidential Suite',
    floor: 3,
  },
];

// Mock bookings data
export const mockBookings = [
  {
    id: 1,
    guestName: 'John Doe',
    phoneNumber: '+1 (123) 456-7890',
    checkInDate: '2023-04-28',
    checkOutDate: '2023-05-01',
    roomType: 'double',
    roomNumber: '201',
    specialRequests: 'Early check-in requested',
    isCheckedOut: false,
    isCancelled: false,
    services: [1, 2], // Room Service and Housekeeping
  },
  {
    id: 2,
    guestName: 'Jane Smith',
    phoneNumber: '+1 (234) 567-8901',
    checkInDate: '2023-05-05',
    checkOutDate: '2023-05-08',
    roomType: 'single',
    roomNumber: '102',
    specialRequests: 'Extra pillows please',
    isCheckedOut: false,
    isCancelled: false,
    services: [3], // Spa Treatment
  },
  {
    id: 3,
    guestName: 'Michael Brown',
    phoneNumber: '+1 (345) 678-9012',
    checkInDate: '2023-04-20',
    checkOutDate: '2023-04-25',
    roomType: 'suite',
    roomNumber: '301',
    specialRequests: '',
    isCheckedOut: true,
    isCancelled: false,
    services: [1, 5, 4], // Room Service, Laundry, Airport Shuttle
  },
  {
    id: 4,
    guestName: 'Lisa Williams',
    phoneNumber: '+1 (456) 789-0123',
    checkInDate: '2023-04-22',
    checkOutDate: '2023-04-24',
    roomType: 'single',
    roomNumber: '101',
    specialRequests: 'Late checkout requested',
    isCheckedOut: true,
    isCancelled: false,
    services: [], // No services
  },
  {
    id: 5,
    guestName: 'David Johnson',
    phoneNumber: '+1 (567) 890-1234',
    checkInDate: '2023-05-10',
    checkOutDate: '2023-05-15',
    roomType: 'suite',
    roomNumber: '302',
    specialRequests: 'Anniversary celebration',
    isCheckedOut: false,
    isCancelled: true,
    services: [3, 4], // Spa Treatment and Airport Shuttle
  },
];

// Mock services data
export const mockServices = [
  {
    id: 1,
    name: 'Room Service',
    category: 'food',
    price: 15.99,
    description: 'In-room dining with a variety of menu options',
    availability: 'Daily, 6am - 11pm',
    status: 'available',
  },
  {
    id: 2,
    name: 'Housekeeping',
    category: 'cleaning',
    price: 0,
    description: 'Daily room cleaning and linen change',
    availability: 'Daily, 9am - 5pm',
    status: 'available',
  },
  {
    id: 3,
    name: 'Spa Treatment',
    category: 'spa',
    price: 89.99,
    description: 'Full spa treatment including massage and facial',
    availability: 'Daily, 10am - 8pm',
    status: 'available',
  },
  {
    id: 4,
    name: 'Airport Shuttle',
    category: 'transport',
    price: 29.99,
    description: 'Transportation to and from the airport',
    availability: 'Upon request, 24/7',
    status: 'available',
  },
  {
    id: 5,
    name: 'Laundry Service',
    category: 'cleaning',
    price: 25.99,
    description: 'Garment cleaning and pressing service',
    availability: 'Daily, 8am - 6pm',
    status: 'available',
  },
  {
    id: 6,
    name: 'Gym Access',
    category: 'entertainment',
    price: 10.99,
    description: 'Access to our fully equipped gym',
    availability: 'Daily, 6am - 10pm',
    status: 'maintenance',
  },
];

// Mock invoices data
export const mockInvoices = [
  {
    id: 'INV-2023-001',
    guestName: 'John Doe',
    roomNumber: '201',
    roomType: 'double',
    checkInDate: '2023-04-28',
    checkOutDate: '2023-05-01',
    date: '2023-05-01',
    dueDate: '2023-05-08',
    status: 'paid',
    roomRate: 149.99,
    roomTotal: 449.97,
    items: [
      {
        description: 'Room Service',
        quantity: 2,
        rate: 15.99,
        amount: 31.98,
      },
      {
        description: 'Mini Bar',
        quantity: 1,
        rate: 25.50,
        amount: 25.50,
      },
    ],
    total: 507.45,
    notes: '',
  },
  {
    id: 'INV-2023-002',
    guestName: 'Jane Smith',
    roomNumber: '102',
    roomType: 'single',
    checkInDate: '2023-05-05',
    checkOutDate: '2023-05-08',
    date: '2023-05-08',
    dueDate: '2023-05-15',
    status: 'unpaid',
    roomRate: 99.99,
    roomTotal: 299.97,
    items: [
      {
        description: 'Spa Treatment',
        quantity: 1,
        rate: 89.99,
        amount: 89.99,
      },
    ],
    total: 389.96,
    notes: '',
  },
  {
    id: 'INV-2023-003',
    guestName: 'Michael Brown',
    roomNumber: '301',
    roomType: 'suite',
    checkInDate: '2023-04-20',
    checkOutDate: '2023-04-25',
    date: '2023-04-25',
    dueDate: '2023-05-02',
    status: 'paid',
    roomRate: 249.99,
    roomTotal: 1249.95,
    items: [
      {
        description: 'Room Service',
        quantity: 3,
        rate: 15.99,
        amount: 47.97,
      },
      {
        description: 'Laundry Service',
        quantity: 1,
        rate: 25.99,
        amount: 25.99,
      },
      {
        description: 'Airport Shuttle',
        quantity: 1,
        rate: 29.99,
        amount: 29.99,
      },
    ],
    total: 1353.90,
    notes: '',
  },
  {
    id: 'INV-2023-004',
    guestName: 'Lisa Williams',
    roomNumber: '101',
    roomType: 'single',
    checkInDate: '2023-04-22',
    checkOutDate: '2023-04-24',
    date: '2023-04-24',
    dueDate: '2023-05-01',
    status: 'overdue',
    roomRate: 99.99,
    roomTotal: 199.98,
    items: [],
    total: 199.98,
    notes: 'Second notice sent',
  },
];

// Mock feedback data
export const mockFeedbacks = [
  {
    id: 1,
    guestName: 'John Doe',
    email: 'john.doe@example.com',
    roomNumber: '201',
    checkInDate: '2023-04-28',
    checkOutDate: '2023-05-01',
    rating: 4,
    title: 'Great stay overall',
    comment: 'The room was clean and comfortable. Staff was very friendly and helpful. Would definitely stay here again.',
    category: 'general',
    status: 'reviewed',
    createdAt: '2023-05-02',
  },
  {
    id: 2,
    guestName: 'Jane Smith',
    email: 'jane.smith@example.com',
    roomNumber: '102',
    checkInDate: '2023-05-05',
    checkOutDate: '2023-05-08',
    rating: 3,
    title: 'Decent stay with a few issues',
    comment: 'The room was nice but the air conditioning was a bit noisy. Breakfast was excellent though.',
    category: 'room',
    status: 'pending',
    createdAt: '2023-05-09',
  },
  {
    id: 3,
    guestName: 'Michael Brown',
    email: 'michael.brown@example.com',
    roomNumber: '301',
    checkInDate: '2023-04-20',
    checkOutDate: '2023-04-25',
    rating: 5,
    title: 'Exceptional experience',
    comment: 'The suite was amazing with a beautiful view. The staff went above and beyond to make our stay special.',
    category: 'service',
    status: 'reviewed',
    createdAt: '2023-04-26',
  },
  {
    id: 4,
    guestName: 'Lisa Williams',
    email: 'lisa.williams@example.com',
    roomNumber: '101',
    checkInDate: '2023-04-22',
    checkOutDate: '2023-04-24',
    rating: 2,
    title: 'Disappointing stay',
    comment: 'The room was not very clean and there were issues with the bathroom plumbing. Staff was responsive but couldn\'t fully resolve the issues.',
    category: 'cleanliness',
    status: 'resolved',
    createdAt: '2023-04-25',
  },
];